### PR TITLE
add kg-resources

### PR DESCRIPTION
**Pull request by lambdaFun94**

### CODE REVIEW

**Comment by mkilpatrick** [comment]
Idk that the starter is the appropriate place for CaC resources. Shouldn't those go into a solution template repo?

**Comment by lambdaFun94** [comment]
@mkilpatrick would you be able to merge for me once it looks good?

**Comment by mkilpatrick** [comment]
> @mkilpatrick would you be able to merge for me once it looks good?

Can do. Didn't we want to change the folder name though?

**Comment by lambdaFun94** [comment]
@mkilpatrick just moved it to platform config

**Review by mkilpatrick — APPROVED** [review]

**Pull request merged**
